#!/usr/bin/bash
                                                                                                                                                                                                             
#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:02:00
#PBS -N Hryshchuk_GrandTotal
                                                                                                                                                                                                             
cd $PBS_O_WORKDIR
                                                                                                                                                                                                             
cat solvOut_{1..240}.out | awk 'BEGIN{x=0}{x+=$0}END{print x}' >GT.out